source(file.path("..", "app.R"), local = TRUE)

test_that("model selection automatically updates a chart visible above the fold", {
  withr::local_envvar(c(NOT_CRAN = "true", LMPLOT_TRUSTED_LOCAL = NA))
  app <- shinytest2::AppDriver$new("..", name = "automatic-chart", width = 1440, height = 900,
    load_timeout = 1e5, timeout = 1e5)
  on.exit(app$stop(), add = TRUE)
  app$wait_for_idle()
  has_plot <- app$get_js("Boolean(document.querySelector('#overview-main_plot')?.data?.length)")
  expect_true(has_plot)
  if (!isTRUE(has_plot)) return()
  app$set_inputs(`configuration-model_type` = "glm_poisson")
  app$wait_for_js("document.querySelector('#overview-chart_summary')?.textContent.includes('Poisson GLM')")
  app$set_inputs(`configuration-data_source` = "real")
  app$wait_for_js("document.querySelector('#overview-chart_summary')?.textContent.includes('4177 observations')")
  app$set_inputs(main_nav_tabs = "data_provenance")
  app$wait_for_idle()
  expect_equal(nrow(read.csv(app$get_download("data_provenance-download"))), 4177L)
  app$set_inputs(main_nav_tabs = "overview")
  app$wait_for_idle()
  bounds <- app$get_js("(() => {const r=document.querySelector('#overview-main_plot').getBoundingClientRect(); return {top:r.top,bottom:r.bottom};})()")
  expect_lt(bounds$top, 300)
  expect_lt(bounds$bottom, 850)
  expect_false(app$get_js("Array.from(document.querySelectorAll('#overview details')).some(x=>x.open)"))
  app$set_inputs(main_nav_tabs = "brain")
  app$wait_for_js("document.querySelector('#brain-contribution_plot')?.data?.length > 0")
  charts <- app$get_js("['contribution','link'].map(k=>{const r=document.querySelector('#brain-'+k+'_plot').getBoundingClientRect();return {top:r.top,width:r.width,height:r.height};})")
  expect_equal(charts[[1]]$top, charts[[2]]$top, tolerance = 2)
  expect_equal(charts[[1]]$height, charts[[2]]$height, tolerance = 2)
  expect_gt(charts[[1]]$width, 300)
  app$set_inputs(`configuration-model_type` = "glmm")
  app$wait_for_js("document.querySelector('#brain-observation_summary')?.textContent.includes('of 4059')")
  enabled <- app$get_js("(() => {const s=document.querySelector('#brain-prediction_mode-selectized');const e=s || document.querySelector('#brain-prediction_mode');return !e.disabled && e.matches(':enabled');})()")
  expect_true(enabled)
  if (!isTRUE(enabled)) return()
  app$run_js("document.querySelector('#brain-prediction_mode').focus()")
  browser <- app$get_chromote_session()
  browser$Input$dispatchKeyEvent(type = 'keyDown', key = 'ArrowDown', code = 'ArrowDown', windowsVirtualKeyCode = 40L)
  browser$Input$dispatchKeyEvent(type = 'keyUp', key = 'ArrowDown', code = 'ArrowDown', windowsVirtualKeyCode = 40L)
  app$wait_for_js("document.querySelector('#brain-observation_summary')?.textContent.includes('population')")
  expect_equal(app$get_value(input = 'brain-prediction_mode'), 'population')
})
