stopifnot(getRversion() == "4.6.0", isTRUE(renv::status()$synchronized))
cat(R.version.string, "\n")
print(l10n_info())
required <- c("renv", "shiny", "plotly", "bslib", "DT", "ggplot2", "ggfortify", "lme4", "jsonlite", "shinyWidgets", "shinyAce", "testthat", "shinytest2", "chromote", "yaml")
stopifnot(all(vapply(required, requireNamespace, logical(1), quietly=TRUE)))
packages <- installed.packages()
print(packages[intersect(required, rownames(packages)), c("Package","Version","Built"), drop=FALSE])
stopifnot(file.exists(Sys.getenv("CHROMOTE_CHROME")))
local({
  browser <- chromote::ChromoteSession$new()
  on.exit(browser$close())
  print(browser$Browser$getVersion())
})
results <- testthat::test_dir("tests", reporter="summary", stop_on_failure=FALSE)
evidence <- as.data.frame(results)
write.csv(evidence[c("file","test","failed","error","warning","skipped","passed")], "docs/release-evidence/local-full-ci-fixes-2026-10-01.csv", row.names=FALSE)
cat("TOTAL files:", length(unique(evidence$file)), "tests:", nrow(evidence), "passed:", sum(evidence$passed), "failed:", sum(evidence$failed), "errors:", sum(evidence$error), "skips:", sum(evidence$skipped), "warnings:", sum(evidence$warning), "\n")
stopifnot(!any(evidence$failed > 0L | evidence$error | evidence$skipped))
